<?php
/**
 * @file nc_content.install
 * Install procedures.
 */

/**
 * Implements hook_install().
 */
function nc_content_install() {
  db_update('system')
    ->fields(array('weight' => 100))
    ->condition('name', 'nc_content', '=')
    ->execute();
}

/**
 * Implements hook_update_N().
 * Adjust module weight for nc_content.
 */
function nc_content_update_7001() {
  db_update('system')
    ->fields(array('weight' => 100))
    ->condition('name', 'nc_content', '=')
    ->execute();
}
