<?php
/**
 * @file
 * Code for the NC Content feature.
 */


/**
 * Implements hook_menu().
 */
function nc_content_menu() {

  $items['admin/content2'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => t('Admin Content'),
    'weight' => -9,
    'description' => 'My custom and very special page',
    'page callback' => 'nc_content_my_page',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    );

  return $items;
}

function nc_content_node_get_title_fast() {
  $result = db_select('node', 'n')
  // ->join('users', 'u', 'n.uid = u.uid') //JOIN node with users
  ->fields('n', array('nid', 'title', 'type', 'uid', 'changed'))
  ->orderBy('changed', 'DESC')//ORDER BY created
  // ->fields('u',array('name'))//SELECT the fields from user
  ->extend('PagerDefault')
  ->limit(30)
  ->execute()
  ->fetchAll();

  return $result;
}

function nc_content_my_page() {
  // Create some data
  $node_table = nc_content_node_get_title_fast();
  $table = '';
  // var_dump($node_table);
  // die();

  foreach ($node_table as $item) {
    $table .= '<tr><td>';
    $table .= '<a href=\'/node/' . $item->nid . '\'>' . $item->title . '</a></td>';
    $table .= '<td>' . $item->type . '</td>';
    $table .= '<td><a href=\'/user/' . $item->uid . '\'>' . $item->uid . '</a></td>';
    $table .= '<td><a href=\'/node/' . $item->nid . '/edit\'>edit</a></td>';
    $table .= '<td><a href=\'/node/' . $item->nid . '/delete\'>delete</a></td>';
    $table .= '</tr>';
  }

  $pager .= theme('pager', array('tags' => array()));

  $data = array
  (
    '#markup' => t('
      <tr>
        <td><strong>Title</strong></td>
        <td><strong>Type</strong></td>
        <td><strong>Author</strong></td>
        <td><strong>Edit</strong></td>
        <td><strong>Delete</strong></td>
      </tr>' . $table . ''),
    '#prefix' => '<table id="nc-content-table">',
    '#suffix' => '</table>' . $pager,
    );

  // Create a $page render array that will be returned
  // from your callback. Attach the CSS using the #attached
  // element of this array
  $page = array
  (
    'nc_content_my_page' => array
    (
      // Note - we will register theme_my_page in the next step
      '#theme' => 'nc-content-theme',
      '#contents' => $data,
      )
    // '#attached' => array
    // (
    //   'css' => array
    //   (
    //     array
    //     (
    //       'type' => 'file',
    //       'data' => drupal_get_path('module', 'nc_content') . '/css/my_page.css',
    //     ),
    //   ),
    // ),
    );

  return $page;
}


function nc_content_theme()
{
  return array
  (
    'nc-content-theme' => array
    (
      'variables' => array('contents' => array()),
      // Register the template my-page.tpl.php
      'template' => 'nc_content-page', // don't add .tpl.php
      ),
    );
}